### ISSUE TITLE
Tests fail in strict mode

### ISSUE THREAD

**Issue by kborowinski** [dfinke/PowerShellAI#98]
Tests fail in `StrictMode`:
![image](https://user-images.githubusercontent.com/16168755/229181773-293ecdda-41ba-4602-ac62-6bf389faf80a.png)

@dfinke: I have working PR fixing this issue already if you are interested.

**Comment by dfinke** [comment]
Sweet. What is the general solution? Is that a v5.1 thing?

**Comment by kborowinski** [comment]
Nope. Count fails on 7.3 and 5.1 when running in strict mode because result is not an array, and on 5.1 you have to check for version before accessing the IsWindows variable.

**Comment by dfinke** [comment]
I believe these are resolved.

**Comment by kborowinski** [comment]
@dfinke  Nope. They still fail in `StrictMode` on PowerShell 5.1 and 7.3.4.

**PS 5.1:**
![image](https://user-images.githubusercontent.com/16168755/233163281-6a69a3ed-060e-4241-9cb6-049bad22da4b.png)

**PS 7.3.4:**
![image](https://user-images.githubusercontent.com/16168755/233163616-3124ab0b-d453-4c26-868f-d205288763d2.png)

And on **PS 5.1** even with `StrictMode -Off`:
![image](https://user-images.githubusercontent.com/16168755/233164131-f6786c73-7052-422b-9bb8-5ab77b95dc95.png)

**Comment by dfinke** [comment]
Will review down the road.
